# Generated by Django 6.0.4 on 2026-05-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
